on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    
    - name: Create Environment Variable
      run : |
        echo "DB_URL=${{ secrets.DB_URL }}" >> .env
        echo "APP_KEY=${{secrets.APP_KET }}" >> .env
        ls
        cat .env

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4


      with:
        server: 109.205.177.80
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        server-dir: public_html/school-platform-api/